name: Build and Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Validate and Build Bicep Files
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install Azure CLI and Bicep CLI
    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install

    # Validate the Bicep files
    - name: Validate Bicep Templates
      run: |
        az bicep build --file main.bicep --stdout

  deploy:
    name: Deploy Infrastructure
    needs: build
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: my-resource-group
      PARAMETERS_FILE: main.parameters.json

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Login to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy the Bicep file
    - name: Deploy Bicep File
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --name main-$(date +%s) \
            --template-file main.bicep \
            --parameters @$PARAMETERS_FILE
