name: deploy-infra

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
      branches:
        - 'main'

env:

  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b

  USER_ALIAS: sverdugo

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
      # Lint Bicep code 
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep
      
      - name: Upload Bicep build artifact
        uses: actions/upload-artifact@v3

        with:
          name: bicep-build
          path: ./main.bicep 
      
        # Checkout the repository to the runner.
      - name: Checkout
        uses: actions/checkout@v3


  deploy-infra:
    runs-on: ubuntu-latest
    needs: build-infra

    steps:

    - uses: actions/checkout@main
  
    - name: Download Bicep build artifact
      uses: actions/download-artifact@v3
      with:
          name: bicep-build
    
      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: >
          ./parameters.bicepparam