name: Validate, Build, and Deploy Infrastructure to DEV

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b

jobs:
  build:
    name: Build Bicep Template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install

    - name: Validate Bicep Syntax
      run: |
        az bicep build --file ./main.bicep --stdout

    - name: Upload Built Template
      uses: actions/upload-artifact@v4
      with:
        name: bicep-build
        path: ./main.bicep

  validate_and_deploy:
    name: Validate and Deploy to DEV
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Built Template
      uses: actions/download-artifact@v4
      with:
        name: bicep-build

    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Validate Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: ./parameters/dev.parameters.json
        deploymentMode: Validate

    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: ./parameters/dev.parameters.json
        deploymentMode: Incremental
